<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="container u-max-width--l">
    <div id="product-review-container" data-role="product-review"></div>
    <?php echo $block->getChildHtml(); ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?php /* @escapeNotVerified */ echo $block->getProductReviewUrl();?>"
            }
        }
    }
</script>
