<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit"
       href="<?php /* @escapeNotVerified */ echo $block->getConfigureUrl() ?>"
       title="<?php echo $block->escapeHtml(__('Edit item parameters')); ?>">
        <span class="i-pencil--s-black" data-grunticon-embed>
            <?php /* @escapeNotVerified */ echo __('Edit') ?>
        </span>
   </a>
<?php endif ?>
