<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<div class="products wrapper products-grid wishlist">
    <?php $iterator = 1; ?>
    <?php if (count($block->getItems())): ?>
    <ol class="o-grid o-grid--has-gutter o-grid--collapse-bottom-gutter products list items product-items">
        <?php foreach ($block->getItems() as $item): ?>
        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="o-grid__cell o-unit-1of2 o-unit-1of3--m item product product-item">' : '</li><li class="o-grid__cell o-unit-1of2 o-unit-1of3--m item product product-item">' ?>
            <div class="product-item-info">
                <?php foreach ($columns as $column): ?>
                    <?php $column->setItem($item); echo $column->toHtml($item);?>
                <?php endforeach; ?>
            </div>
        <?php echo($iterator == count($block->getItems())+1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </ol>
    <?php else: ?>
        <div class="message info empty">
            <span><?php /* @escapeNotVerified */ echo __('This Wish List has no Items');?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
