<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}

$cmsPageId = $this->helper('GPMD\ContentHeading\Helper\Data')->getCmsPageId();
$contentHeadingStatus = $this->helper('GPMD\ContentHeading\Helper\Data')->getContentHeadingStatus($cmsPageId);
?>

<?php if ($contentHeadingStatus !== '0'): ?>
    <?php if ($title): ?>
        <div class="page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?><?php if ($cssClass === ' product'): ?> u-hide--lt-m<?php endif; ?>">
            <h1 class="page-title<?php if ($cssClass === ' product'): ?> h3 u-font-weight--bold<?php else: ?> h2<?php endif; ?>"
                <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
                <?php if ($block->getAddBaseAttributeAria()): ?>
                    aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
                <?php endif; ?>>
                <?php /* @escapeNotVerified */ echo $title ?>
            </h1>
            <?php echo $block->getChildHtml(); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
