<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$isLoggedIn = $this->helper('GPMD\DrawerHeader\Helper\Data')->getIsLoggedIn();
$storeLinksIsEnabled = $this->helper('GPMD\DrawerHeader\Helper\Data')->getStoreLinksIsEnabled();
$storeLinksBlock = $block->getLayout()->createBlock('GPMD\DrawerHeader\Block\StoreSelector');
$storeLinks = $storeLinksBlock->getStoreLinks();
$currentStoreCode = $storeLinksBlock->getStoreCode();
$horizontalNavEnabled = $this->helper('GPMD\DrawerHeader\Helper\Data')->getHorizontalNavEnabled();
?>

<div class="header__sections drawer-toggles">

    <div class="header__section header__section--left">
        <a class="drawer__toggle drawer__toggle--menu" href="#" data-drawer-id="1" data-drawer-direction="left">
            <span class="header__icon i-burger--s-black i--has-hover" data-grunticon-embed></span>
            <span class="header__icon i-burger--s-white i--has-hover" data-grunticon-embed></span>
            <span class="u-hide-text"><?php /* @escapeNotVerified */ echo __('Toggle Main Menu'); ?></span>
        </a>
        <a class="drawer__toggle drawer__toggle--search" href="#" data-drawer-id="2" data-drawer-direction="left">
            <span class="header__icon i-search--s-black i--has-hover" data-grunticon-embed></span>
            <span class="header__icon i-search--s-white i--has-hover" data-grunticon-embed></span>
            <span class="u-hide-text"><?php /* @escapeNotVerified */ echo __('Toggle Search'); ?></span>
        </a>
    </div>

    <div class="header__section header__section--center">
        <?php if ($block->isHomePage()): ?>
        <div class="logo">
            <?php else: ?>
            <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName; ?>">
                <?php endif; ?>
                <img class="logo__img"
                     src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc(); ?>"
                     alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt(); ?>"
                    <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : ''; ?>
                    <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : ''; ?>
                />
                <?php if ($block->isHomePage()): ?>
        </div>
    <?php else: ?>
        </a>
    <?php endif; ?>
        <?php if ($horizontalNavEnabled): ?><?php echo $block->getChildHtml('catalog.horizontal.topnav'); ?><?php endif; ?>
    </div>

    <div class="header__section header__section--right">
        <a class="drawer__toggle drawer__toggle--user<?php if ($isLoggedIn): ?> is-logged-in<?php endif; ?>" href="#" data-drawer-id="3" data-drawer-direction="right">
            <span class="header__icon i-user--s-black i--has-hover" data-grunticon-embed></span>
            <span class="header__icon i-user--s-white i--has-hover" data-grunticon-embed></span>
            <span class="u-hide-text"><?php /* @escapeNotVerified */ echo __('Toggle My Account'); ?></span>
        </a>
        <?php if ($storeLinksIsEnabled): ?>
            <a class="drawer__toggle drawer__toggle--store-selector" href="#" data-drawer-id="4" data-drawer-direction="right">
                <span class="header__icon i-globe--s-black i--has-hover" data-grunticon-embed></span>
                <span class="header__icon i-globe--s-white i--has-hover" data-grunticon-embed></span>
                <span class="country-code"><?php foreach ($storeLinks as $storeLink): ?>
                        <?php if ($storeLink[1] == $currentStoreCode): ?>
                            <span class="country-code__content"><?php echo $storeLink[2] . ' ' . $storeLink[3]; ?></span>
                        <?php endif; ?>
                    <?php endforeach; ?></span>
                <span class="u-hide-text"><?php /* @escapeNotVerified */ echo __('Toggle Store Selector'); ?></span>
            </a>
        <?php endif; ?>
        <a class="drawer__toggle drawer__toggle--bag" href="#" data-drawer-id="5" data-drawer-direction="right">
            <span class="header__icon i-bag--s-black i--has-hover" data-grunticon-embed></span>
            <span class="header__icon i-bag--s-white i--has-hover" data-grunticon-embed></span>
            <span class="cart-count empty" data-synced-cart-count></span>
            <span class="u-hide-text"><?php /* @escapeNotVerified */ echo __('Toggle Bag'); ?></span>
        </a>
    </div>

</div>
