<script type="text/x-magento-init">
    {
        "*": {
            "js/m2base": {},
            "js/wrap-selects": {},
            "js/notification-messages": {}
        },
        ".js-eq-heights__wrapper": {
            "bower_components/equalize-heights/dist/equalize-heights.min": {},
            "js/equalize-heights-init": {}
        },
        ".tablesaw": {
            "bower_components/filament-tablesaw/dist/tablesaw": {},
            "bower_components/filament-tablesaw/dist/tablesaw-init": {}
        },
        "[data-ratio-min]": {
            "js/ratio": {}
        },
        ".js-sticky-header": {
            "js/sticky-header": {}
        },
        "[data-physcroll]": {
            "bower_components/phyScroll/dist/phyScroll.min": {},
            "js/phyScrollInit": {}
        },
        ".o-cover__object": {
            "bower_components/limit.js/limit": {},
            "js/object-cover": {}
        },
        ".js-select-nav": {
            "js/select-nav": {}
        },
        "[data-synced-cart-count]": {
            "js/sync-cart-info": {}
        },
        ".js-tothetop": {
            "js/to-the-top": {}
        },
        "[data-slide-toggle]": {
            "js/slide-toggle": {}
        }
    }
</script>
