<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="container">
        <section class="section">
            <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
                <?php if ($title):?>
                    <div class="block-title u-text-align--center">
                        <h2 class="h3 u-font-weight--bold">
                            <span id="block-products-widget" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></span>
                        </h2>
                    </div>
                <?php endif ?>
                <div class="block-content">
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                        <ol class="o-grid o-grid--has-gutter o-grid--collapse-bottom-gutter items product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="o-grid__cell o-unit-1of1 o-unit-1of2--m o-unit-1of3--l o-unit-1of4--xl o-unit-1of5--xxl product-item">' : '</li><li class="o-grid__cell o-unit-1of1 o-unit-1of2--m o-unit-1of3--l o-unit-1of4--xl o-unit-1of5--xxl product-item">' ?>
                                <div class="product-item-info">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                               class="product-item-link">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php
                                        echo $block->getProductPriceHtml($_item, $type);
                                        ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary"
                                                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if ($showWishlist || $showCompare || $templateType): ?>
                                                    <div class="actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                               class="action towishlist" data-action="add-to-wishlist"
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                                <span class="i-heart--s-black i--has-hover" data-grunticon-embed><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                            <a href="#" class="action tocompare"
                                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                                <span class="i-plus--s-black i--has-hover" data-grunticon-embed><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($templateType): ?>
                                                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                    </div>
                    <?php echo $block->getPagerHtml() ?>
                </div>
            </div>
        </section>
    </div>
<?php endif;?>
